services:
  # 1. API Backend (Python/FastAPI)
  - type: web
    name: candidato-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        sync: false # Pega aquí tu URL de la base de datos desde el panel de Render

  # 2. Frontend (Next.js)
  - type: web
    name: candidato-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: candidato-backend
          envVarKey: RENDER_EXTERNAL_URL
